# Generated by CMake 2.8.10.20121207-g2be87

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

SET(_targetsDefined)
SET(_targetsNotDefined)
SET(_expectedTargets)
FOREACH(_expectedTarget drsyscall umbra)
  LIST(APPEND _expectedTargets ${_expectedTarget})
  IF(NOT TARGET ${_expectedTarget})
    LIST(APPEND _targetsNotDefined ${_expectedTarget})
  ENDIF(NOT TARGET ${_expectedTarget})
  IF(TARGET ${_expectedTarget})
    LIST(APPEND _targetsDefined ${_expectedTarget})
  ENDIF(TARGET ${_expectedTarget})
ENDFOREACH(_expectedTarget)
IF("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  SET(CMAKE_IMPORT_FILE_VERSION)
  CMAKE_POLICY(POP)
  RETURN()
ENDIF("${_targetsDefined}" STREQUAL "${_expectedTargets}")
IF(NOT "${_targetsDefined}" STREQUAL "")
  MESSAGE(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
ENDIF(NOT "${_targetsDefined}" STREQUAL "")
UNSET(_targetsDefined)
UNSET(_targetsNotDefined)
UNSET(_expectedTargets)


# Create imported target drsyscall
ADD_LIBRARY(drsyscall SHARED IMPORTED)

# Create imported target umbra
ADD_LIBRARY(umbra SHARED IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/DRMFTarget32-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
